version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
    - "5432:5432"
    volumes:
    - ./.postgresdata:/var/lib/postgresql/data
    shm_size: 256m
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      TZ: UTC
    networks:
    - sleep-tracker-nt

networks:
  sleep-tracker-nt:
    driver: bridge