version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
    - "5432:5432"
    volumes:
      - ./.postgresdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    shm_size: 256m
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      TZ: UTC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - sleep-tracker-nt
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
    restart: always
    networks:
    - sleep-tracker-nt
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: always
    networks:
    - sleep-tracker-nt

networks:
  sleep-tracker-nt:
    driver: bridge