---
plugins:
  - prettier
  - '@typescript-eslint'

extends:
  - airbnb-base
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript

parser: '@typescript-eslint/parser'

rules:
  complexity:
    - warn
    - 10
  # https://stackoverflow.com/a/59268871/1998477
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
