version: "3"

services:
  postgres:
    image: postgres:15.2
    ports:
      - 10001:5432
    container_name: test-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

